services:
  - type: web
    name: linely-whisper-24-7
    env: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: python render_whisper.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: max_split_size_mb:128
